add_newline = false

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[directory]
style = "blue"

[git_branch]
symbol = "ğŸŒ± "
style = "yellow"

[nodejs]
symbol = "îœ˜ "

[python]
symbol = "ğŸ "

[git_status]
style = "red"
format = '([]() )'
